[server]
port=":8888"
logLevel=2
aeskey="666effd85965dffcffcfdfadf6666666"
mode="test"
#release
ginmode="debug"
rootPath="/code/go/src/happylemon/"
logPath="log/"

[redis]
host="127.0.0.1"
port="6379"
auth=""
db=0

[mysql]
host="127.0.0.1"
username="root"
password="root"
port="3306"
database="j20_api"
maxOpenConns=50
maxIdleConns=5

#一些访问需要做ip限制
[ipWhiteList]
ips=["::1","127.0.0.1","61.148.75.238","172.31.0.*"]

[grpc]
grpcSwitch = true
apiHost="0.0.0.0"
apiPort=":8787"

[sms]
accessKeyId="xxxxxxxx"
accessKeySecret="xxxxxxxx"
signname="阿里云短信测试专用"

[oss]
endpoint="oss-cn-beijing.aliyuncs.com"
ossBucket="happylemon"
ossCdn="http://xxxxx.oss-cn-beijing.aliyuncs.com/"

[upload]
qrLogoPath="/code/go/src/j20/doc/qr-logo.png"
saveDir="/code/go/src/happylemon/resource/"
avatarSaveDir="avatar/"
groupSaveDir="group/"
qrImgSaveDir="qrcode/"
idCardSaveDir="idcard/"
feedsSaveDir="feeds/"
feedsGifSaveDir="feeds_gif/"
#mkdir  avatar group qrcode idcard  feeds feeds_gif


[redisKey]
userPrefix="user:"
tokenPrefix="token:"
tokenUidKey="uid"
CronListKey="cron_list"
QueueListKey="queue_list"
